In [26]:
from db.db_connection import create_connection
import pandas as pd
from utils.formatter import prettify

connection = create_connection()

query = """
SELECT * FROM v_transactions_overview
"""

df = pd.read_sql(query, connection)
connection.close()

prettify(df)

C:\Users\051066\AppData\Local\Temp\ipykernel_17980\57073740.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, connection)

,ID,Customer,Platform,Asset,status,currency,Date,Amount,Buy Price,Buy Price (EUR),Exchange Fee,Service Fee,Referral Bonus
0,1,Anna,Binance,BTC,completed,USD,2025-01-10,0.05,42000.0,38640.0,10.0,5.0,0.0
1,2,Mark,Coinbase,BTC,completed,USD,2025-02-15,0.02,45000.0,41850.0,8.0,4.0,0.0
2,3,Julia,Kraken,BTC,completed,USD,2025-03-01,0.01,47000.0,42770.0,7.0,3.0,1.0
3,4,Tom,Binance,ETH,completed,USD,2025-03-10,1.20,2500.0,2350.0,5.0,2.0,0.0
4,5,Lisa,Coinbase,ETH,completed,USD,2025-04-01,0.80,2600.0,2392.0,6.0,3.0,2.0
5,6,David,Kraken,BTC,pending,USD,2025-04-01,0.03,48000.0,44160.0,9.0,4.0,0.0

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   transaction_id      6 non-null      int64
 1   client_name         6 non-null      str
 2   platform_name       6 non-null      str
 3   asset_symbol        6 non-null      str
 4   status              6 non-null      str
 5   currency            6 non-null      str
 6   transaction_date    6 non-null      object
 7   amount              6 non-null      float64
 8   buy_price           6 non-null      float64
 9   buy_price_eur       6 non-null      float64
 10  exchange_fee_eur    6 non-null      float64
 11  service_fee_eur     6 non-null      float64
 12  referral_bonus_eur  6 non-null      float64
dtypes: float64(6), int64(1), object(1), str(5)
memory usage: 756.0+ bytes

In [28]:
df["total_buy_eur"] = df["amount"] * df["buy_price_eur"]
prettify(df)

,ID,Customer,Platform,Asset,status,currency,Date,Amount,Buy Price,Buy Price (EUR),Exchange Fee,Service Fee,Referral Bonus,Total Investment (EUR)
0,1,Anna,Binance,BTC,completed,USD,2025-01-10,0.05,42000.0,38640.0,10.0,5.0,0.0,1932.0
1,2,Mark,Coinbase,BTC,completed,USD,2025-02-15,0.02,45000.0,41850.0,8.0,4.0,0.0,837.0
2,3,Julia,Kraken,BTC,completed,USD,2025-03-01,0.01,47000.0,42770.0,7.0,3.0,1.0,427.7
3,4,Tom,Binance,ETH,completed,USD,2025-03-10,1.20,2500.0,2350.0,5.0,2.0,0.0,2820.0
4,5,Lisa,Coinbase,ETH,completed,USD,2025-04-01,0.80,2600.0,2392.0,6.0,3.0,2.0,1913.6
5,6,David,Kraken,BTC,pending,USD,2025-04-01,0.03,48000.0,44160.0,9.0,4.0,0.0,1324.8