In [3]:
from matplotlib.backend_bases import cursors

from db.db_connection import create_connection
import pandas as pd
from utils.formatter import prettify
import warnings
warnings.filterwarnings("ignore")
connection = create_connection()

query = """SELECT * FROM v_transactions_overview"""
df = pd.read_sql(query, connection)
prettify(df)

,ID,client_id,Customer,platform_id,Platform,asset_id,Asset,Date,transaction_type,net_amount,Amount,Buy Price,Buy Price (EUR),Exchange Fee,Service Fee,Referral Bonus
0,4,4,Tom,1,Binance,2,ETH,2025-04-10,BUY,1.2000,1.2000,1662.53,1500.203423,5.00,2.00,0.00
1,10,2,Mark,1,Binance,2,ETH,2025-04-14,BUY,0.0202,0.0202,1610.28,1415.390000,4.89,2.28,1.71
2,14,4,Tom,1,Binance,2,ETH,2025-04-23,BUY,0.0426,0.0426,1774.23,1554.290000,2.77,4.95,0.01
3,29,6,David,1,Binance,2,ETH,2025-05-12,BUY,0.4857,0.4857,2528.46,2276.650000,9.24,3.34,3.00
4,40,1,Anna,1,Binance,2,ETH,2025-05-28,BUY,0.2490,0.2490,2687.85,2375.070000,6.60,4.97,0.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,298,3,Julia,3,Kraken,1,BTC,2026-04-08,BUY,0.0284,0.0284,72318.01,62575.330000,9.00,2.99,2.42
316,302,3,Julia,3,Kraken,1,BTC,2026-04-08,BUY,0.0479,0.0479,72113.76,62398.590000,5.58,1.15,0.21
317,314,4,Tom,3,Kraken,1,BTC,2026-04-08,BUY,0.0174,0.0174,72024.85,62321.660000,3.82,4.50,2.77
318,326,3,Julia,3,Kraken,1,BTC,2026-04-08,BUY,0.0198,0.0198,72328.24,62584.180000,6.42,3.92,1.60
319,330,6,David,3,Kraken,1,BTC,2026-04-08,BUY,0.0486,0.0486,72591.72,62812.170000,6.30,3.20,0.13

In [7]:
def run_query(query):
    connection=create_connection()
    df = pd.read_sql(query, connection)
    connection.close()
    return df

In [9]:
df = run_query("""
SELECT * FROM market_prices WHERE DATE(price_date) = CURDATE()
ORDER BY price_id DESC
LIMIT 10""")
df

,price_id,asset_id,price_date,price_usd,eur_rate,price_eur,created_at,updated_at
0,754,2,2026-04-08 19:05:04,2221.72,0.85426,1897.926527,2026-04-08 19:05:07,2026-04-08 19:05:07
1,753,1,2026-04-08 19:05:04,71616.00,0.85426,61178.684160,2026-04-08 19:05:07,2026-04-08 19:05:07
2,752,2,2026-04-08 16:48:36,2207.77,0.86528,1910.339226,2026-04-08 16:48:37,2026-04-08 16:48:37
3,751,1,2026-04-08 16:48:36,71120.00,0.86528,61538.713600,2026-04-08 16:48:37,2026-04-08 16:48:37
4,750,2,2026-04-08 14:59:05,2254.64,0.86528,1950.894899,2026-04-08 14:59:05,2026-04-08 14:59:05
5,749,1,2026-04-08 14:59:05,71977.00,0.86528,62280.258560,2026-04-08 14:59:05,2026-04-08 14:59:05
6,748,2,2026-04-08 13:05:02,2242.56,0.86528,1940.442317,2026-04-08 13:05:03,2026-04-08 13:05:03
7,747,1,2026-04-08 13:05:02,71490.00,0.86528,61858.867200,2026-04-08 13:05:03,2026-04-08 13:05:03
8,746,2,2026-04-08 10:50:02,2253.14,0.86528,1949.596979,2026-04-08 10:50:02,2026-04-08 10:50:02
9,745,1,2026-04-08 10:50:02,71717.00,0.86528,62055.285760,2026-04-08 10:50:02,2026-04-08 10:50:02

In [20]:
df= run_query("""DESCRIBE transactions""")
df

,Field,Type,Null,Key,Default,Extra
0,transaction_id,int unsigned,NO,PRI,NaN,auto_increment
1,client_id,int unsigned,NO,MUL,NaN,
2,platform_id,int unsigned,NO,MUL,NaN,
3,asset_id,int unsigned,NO,MUL,NaN,
4,status_id,int unsigned,NO,MUL,NaN,
5,transaction_date,date,NO,MUL,NaN,
6,amount,"decimal(18,8)",NO,,NaN,
7,buy_price,"decimal(18,8)",NO,,NaN,
8,currency_id,int unsigned,NO,MUL,NaN,
9,buy_price_eur,"decimal(18,8)",NO,,NaN,
10,exchange_fee_eur,"decimal(18,8)",NO,,0.00000000,
11,service_fee_eur,"decimal(18,8)",NO,,0.00000000,
12,referral_bonus_eur,"decimal(18,8)",NO,,0.00000000,
13,transaction_type,"enum('BUY','SELL')",NO,MUL,BUY,
14,created_at,timestamp,YES,,CURRENT_TIMESTAMP,DEFAULT_GENERATED
15,updated_at,timestamp,YES,,CURRENT_TIMESTAMP,DEFAULT_GENERATED on update CURRENT_TIMESTAMP

In [24]:
df = run_query(""" select * from transactions order by transaction_id desc limit 5""")
df

,transaction_id,client_id,platform_id,asset_id,status_id,transaction_date,amount,buy_price,currency_id,buy_price_eur,exchange_fee_eur,service_fee_eur,referral_bonus_eur,transaction_type,created_at,updated_at
0,223,2,1,1,2,2026-04-06,0.0301,70229.25,1,60936.51,6.29,2.41,0.39,BUY,2026-04-06 22:24:13,2026-04-06 22:24:13
1,222,3,3,2,1,2026-04-06,0.2412,2175.53,1,1887.66,5.36,1.70,2.62,BUY,2026-04-06 22:24:13,2026-04-06 22:24:13
2,221,1,2,1,1,2026-04-06,0.0338,70057.87,1,60787.82,9.49,4.48,1.51,BUY,2026-04-06 18:21:14,2026-04-06 18:21:14
3,220,2,3,1,1,2026-04-06,0.0270,70673.93,1,61322.36,5.06,4.44,1.27,BUY,2026-04-06 18:21:14,2026-04-06 18:21:14
4,219,6,2,2,2,2026-04-06,0.3040,2170.32,1,1883.14,2.33,1.08,0.04,BUY,2026-04-06 15:21:12,2026-04-06 15:21:12

In [ ]:
df= run_query("""select * from tr""")

In [2]:
df = run_query("""SELECT mp.*
FROM market_prices mp
JOIN (
    SELECT asset_id, MAX(price_date) AS max_date
    FROM market_prices
    GROUP BY asset_id
) latest
ON mp.asset_id = latest.asset_id
AND mp.price_date = latest.max_date;""")
df

NameError: name 'run_query' is not defined

In [6]:
df=run_query("SHOW TABLES")
df

    Tables_in_crypto_portfolio_db
0                       abo_types
1                     asset_types
2                          assets
3                         clients
4                       countries
5                      currencies
6                   market_prices
7                       platforms
8                        statuses
9                    transactions
10  v_market_prices_latest_simple
11     v_portfolio_balance_simple
12       v_portfolio_value_simple
13        v_transactions_overview

In [7]:
df=run_query("DESCRIBE transactions")
df

,Field,Type,Null,Key,Default,Extra
0,transaction_id,int unsigned,NO,PRI,NaN,auto_increment
1,client_id,int unsigned,NO,MUL,NaN,
2,platform_id,int unsigned,NO,MUL,NaN,
3,asset_id,int unsigned,NO,MUL,NaN,
4,status_id,int unsigned,NO,MUL,NaN,
5,transaction_date,date,NO,MUL,NaN,
6,amount,"decimal(18,8)",NO,,NaN,
7,buy_price,"decimal(18,8)",NO,,NaN,
8,currency_id,int unsigned,NO,MUL,NaN,
9,buy_price_eur,"decimal(18,8)",NO,,NaN,
10,exchange_fee_eur,"decimal(18,8)",NO,,0.00000000,
11,service_fee_eur,"decimal(18,8)",NO,,0.00000000,
12,referral_bonus_eur,"decimal(18,8)",NO,,0.00000000,
13,transaction_type,"enum('BUY','SELL')",NO,MUL,BUY,
14,created_at,timestamp,YES,,CURRENT_TIMESTAMP,DEFAULT_GENERATED
15,updated_at,timestamp,YES,,CURRENT_TIMESTAMP,DEFAULT_GENERATED on update CURRENT_TIMESTAMP

In [8]:
df=run_query("DESCRIBE market_prices")
df

,Field,Type,Null,Key,Default,Extra
0,price_id,int unsigned,NO,PRI,NaN,auto_increment
1,asset_id,int unsigned,NO,MUL,NaN,
2,price_date,datetime,NO,MUL,NaN,
3,price_usd,"decimal(18,2)",YES,,NaN,
4,eur_rate,"decimal(10,6)",YES,,NaN,
5,price_eur,"decimal(18,8)",NO,,NaN,
6,created_at,timestamp,YES,,CURRENT_TIMESTAMP,DEFAULT_GENERATED
7,updated_at,timestamp,YES,,CURRENT_TIMESTAMP,DEFAULT_GENERATED on update CURRENT_TIMESTAMP

In [9]:
df = run_query("""SELECT COUNT(*) FROM transactions""")
df

   COUNT(*)
0       223

In [10]:
df= run_query("SELECT * FROM v_transactions_overview")
df

,transaction_id,client_name,platform_name,asset_symbol,status_name,currency_code,transaction_date,transaction_type,amount,buy_price,buy_price_eur,exchange_fee_eur,service_fee_eur,referral_bonus_eur
0,4,Tom,Binance,ETH,completed,USD,2025-03-10,BUY,1.2000,2500.00,2350.00,5.00,2.00,0.00
1,10,Mark,Binance,ETH,completed,USD,2025-04-14,BUY,0.0202,1610.28,1415.39,4.89,2.28,1.71
2,14,Tom,Binance,ETH,completed,USD,2025-04-23,BUY,0.0426,1774.23,1554.29,2.77,4.95,0.01
3,29,David,Binance,ETH,pending,USD,2025-05-12,BUY,0.4857,2528.46,2276.65,9.24,3.34,3.00
4,40,Anna,Binance,ETH,completed,USD,2025-05-28,BUY,0.2490,2687.85,2375.07,6.60,4.97,0.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,198,Julia,Kraken,BTC,pending,USD,2026-03-08,BUY,0.0392,67854.11,58692.45,3.58,3.28,0.97
219,199,Julia,Kraken,BTC,completed,USD,2026-03-09,SELL,0.0056,65633.02,56800.78,3.92,4.71,2.21
220,207,Tom,Kraken,BTC,completed,USD,2026-03-30,SELL,0.0196,65401.16,56950.02,8.90,1.39,0.59
221,209,Tom,Kraken,BTC,pending,USD,2026-03-31,BUY,0.0412,67158.14,58408.78,3.23,2.29,0.20
222,220,Mark,Kraken,BTC,pending,USD,2026-04-06,BUY,0.0270,70673.93,61322.36,5.06,4.44,1.27